mybatis:
  type-aliases-package: com.guo.methodology.domain
  mapper-locations: classpath:mybatis/mapper/com/guo/methodology/dao/*.xml

spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.51:3306/spring-boot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456